### ISSUE TITLE
hey i appreciate what you did here , any way to implement this with angular monaco compenent? 

### ISSUE THREAD

**Issue by mnmajd** [Pranomvignesh/restrict_editarea_monaco_editor#1]

**Comment by Pranomvignesh** [comment]
Hi @mnmajd , There is a recent update on the restricted editor implementation which purely relies on the ranges, And I am planning to release this as an npm package soon. Once released, you can follow the documentation on how to use it in any javascript application.

If you have any urgent requirement, feel free to look into my code and recreate your own implementation using my source files as a base

_PS: I don't know much about angular, I can help you with JS but you have to take care of the data binding and event handling layer in the angular implementation_

**Comment by mnmajd** [comment]
Hi @Pranomvignesh  , thank you for reply , can you put the old version in another please? its suits with my case 
i will try to adapt it with what im really want to implement in my project

**Comment by Pranomvignesh** [comment]
`can you put the old version in another please` - I have created a tag named [old version](https://github.com/Pranomvignesh/restrict_editarea_monaco_editor/releases/tag/old-version) from the commit id c27a2db60d5f50e22d60ec6f1b7e82a521dce4b5 , you can use that for your case
